app:
  timeout: 3s #seconds

engine:
  type: "in_memory"

network:
  address: "127.0.0.1:8088"
  max_connections: 10

wal:
  flushing_batch_size: 2
  flushing_batch_timeout: "1000s"
  max_segment_size: "2KB"
  data_directory: "./wal_logs/wal"

logger:
  level: debug
  is_pretty: true
