app:
  timeout: 3s #seconds

engine:
  type: "in_memory"

wal:
  is_write_to_wal: false
#  flushing_batch_size: 2
#  flushing_batch_timeout: "10s"
#  max_segment_size: "2KB"
#  data_directory: "./wal_logs/wal"

network:
  address: "127.0.0.1:8089"
  max_connections: 10

replication:
  replica_type: "slave"
  master_address: "127.0.0.1:8088"
  sync_interval: "1s"

logger:
  level: debug
  is_pretty: true
